routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('ADs',App\Http\Controllers\ADController::class);

app/Models/AD.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AD extends Model
{
    use HasFactory;

    protected $fillable = ['id','title','image','target_url'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ADController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ADsRequest;
use App\Http\Requests\ImagesRequest;
use App\Models\AD;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use File;
class ADController extends Controller
{
    public function index(){
        $Ads = AD::all();
        return view('ADs.index')->with('Ads',$Ads);
    }

    public function create(){
        return view('ADs.create');
    }

    public function store(ADsRequest $request){
        $image = $request->file('image');
        $imageName = $image->getClientOriginalName();
        $destinationPath = public_path('\\upload');
        $img = Image::make($image->path());
        $img->resize(900,600)
            ->save($destinationPath.'\\'.$imageName);

        AD::create([
            'title'=> $request->title,
            'image'=>$imageName,
            'target_url'=>$request->target_url
        ]);
        return redirect(route('ADs.index'));
    }


    public function edit($AD){
        $Ads = AD::find($AD);
        return view('ADs.edit')->with('Ads',$Ads);
    }

    public function update(ADsRequest $request ,$AD){
        $Ads = AD::find($AD);
        $destinationPath = public_path('\\upload\\'.$Ads->image);
        if (File::exists($destinationPath)) File::delete($destinationPath);

        $image = $request->file('image');
        $imageName = $image->getClientOriginalName();
        $destinationPath = public_path('\\upload');
        $img = Image::make($image->path());
        $img->resize(900,600)
            ->save($destinationPath.'\\'.$imageName);

        $Ads->update([
           'title'=>$request->title,
           'image'=>$imageName,
           'target_url'=>$request->target_url
        ]);
        return redirect(route('ADs.index'));
    }

    public function destroy($AD){

        $Ads = AD::find($AD);
        if (File::exists(public_path('\\upload\\'.$Ads->image))) File::delete(public_path('\\upload\\'.$Ads->image));
        $Ads->delete();
        return redirect(route('ADs.index'));
    }
}

app/Http/Controllers/API/ADController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Resources\ADResource;
use App\Models\AD;
use Illuminate\Http\Request;

class ADController extends Controller
{
    public function index(): \Illuminate\Http\Resources\Json\AnonymousResourceCollection
    {
        $ADs = AD::all();
        return  ADResource::collection($ADs);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\AD;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $ADs  = AD::all();
        return view('home')->with('ADs',$ADs);
    }
}

resources/views/ADs/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


        <form action="{{ route('ADs.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <br/>
                    <input type="text" name="title" class="form-control" placeholder="Add Title">
                </div>
                <div class="col-md-12">
                    <br/>
                    <input type="text" name="target_url" class="form-control" placeholder="Add Target URL">
                </div>
                <div class="col-md-12">
                    <br/>
                    <input type="file" name="image" class="image">
                </div>
                <div class="col-md-12">
                    <br/>
                    <button type="submit" class="btn btn-success">Upload Image</button>
                </div>
            </div>
        </form>
    </div>

    @endsection

resources/views/ADs/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


        <form action="{{ route('ADs.update',$Ads->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <br/>
                    <input type="text" name="title" class="form-control" placeholder="Add Title" value="{{$Ads->title}}">
                </div>
                <div class="col-md-12">
                    <br/>
                    <input type="text" name="target_url" class="form-control" placeholder="Add Target URL" value="{{$Ads->target_url}}">
                </div>
                <div class="col-md-12">
                    <br/>
                    <input type="file" name="image" class="image">
                </div>
                <div class="col-md-12">
                    <br/>
                    <button type="submit" class="btn btn-success">Update Image</button>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/ADs/index.blade.php
@extends('layouts.app')
@section('content')
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Target URL</th>
            <th scope="col">Image</th>
            <th scope="col">ِActions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($Ads as $Ad)
        <tr>
            <th scope="row">{{$Ad->id}}</th>
            <td>{{$Ad->title}}</td>
            <td>{{$Ad->target_url}}</td>
            <td>{{$Ad->image}}</td>
            <td>
                <a href="{{route('ADs.edit',$Ad->id)}}" class="btn btn-primary"><span class="fa fa-edit fa-1x"></span></a>
            </td>
            <td>
                    <form action="{{route('ADs.destroy',$Ad->id)}}" method="post"  enctype="multipart/form-data"  id="delete-form" class="actions-buttons">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit"><span class="fa fa-trash fa-1x delete-btn"></span></button>
                    </form>
            </td>

        </tr>
        @endforeach
        </tbody>
    </table>


@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                        <hr>

                        <div class="justify-content-center">
                            <a href="{{route('ADs.create')}}"class="btn btn-info">Upload Image</a>
                            <hr>
                            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                                </ol>
                                <div class="carousel-inner">
                                    @foreach($ADs as $key => $AD)
                                    <div class="carousel-item {{$key == 0 ? 'active' : '' }}">
                                            <img class="d-block w-100" src="{{asset('upload/'.$AD->image)}}" alt="{{$AD->title}}">
                                            <div class="carousel-caption d-none d-md-block">
                                                <h5>{{$AD->title}}</h5>
                                                <a href="{{$AD->target_url}}
                                                    ">{{$AD->target_url}}</a>
                                            </div>
                                        </div>
                                    @endforeach

                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Plansters</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Plansters
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest

                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>